export type GeographicalIndicationEntry = {
  serial: string
  name: string
  type: string
  year: string
}

export type GeographicalIndicationStateGroup = {
  state: string
  items: readonly GeographicalIndicationEntry[]
}

export const geographicalIndicationByState: readonly GeographicalIndicationStateGroup[] = [
  {
    state: 'Andaman and Nicobar Islands',
    items: [
      {
        serial: '644',
        name: 'Andaman Karen Musley rice',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Andhra Pradesh',
    items: [
      {
        serial: '22',
        name: 'Srikalahasthi Kalamkari',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '31',
        name: 'Kondapalli bommallu',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '71',
        name: 'Machilipatnam Kalamkari',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '88',
        name: 'Budithi Bell and Brass Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '93',
        name: 'Andhra Pradesh leather puppetry',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '106',
        name: 'Uppada Jamdani sarees',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '107',
        name: 'Tirupathi Laddu',
        type: 'Food stuff',
        year: '2009–10',
      },
      {
        serial: '122',
        name: 'Guntur Sannam Chilli',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '151',
        name: 'Venkatagiri Sarees',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '162',
        name: 'Bobbili Veena',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '179',
        name: 'Mangalagiri sarees and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '207',
        name: 'Dharmavaram handloom pattu sarees and paavadas',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '286',
        name: 'Bandar Laddu',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '288',
        name: 'Udayagiri Wooden Cutlery',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '298',
        name: 'Durgi Stone Carvings',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '299',
        name: 'Etikoppaka Toys',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '310',
        name: 'Allagadda Stone Carving',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '483',
        name: 'Atreyapuram Pootharekulu',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '565',
        name: 'Narasapur Crochet Lace Products',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '645',
        name: 'Ponduru Khadi',
        type: 'Textiles',
        year: '2024-25',
      },
    ],
  },
  {
    state: 'Andhra Pradesh, Odisha',
    items: [
      {
        serial: '334',
        name: 'Araku Valley Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
    ],
  },
  {
    state: 'Arunachal Pradesh',
    items: [
      {
        serial: '221',
        name: 'Arunachal Orange',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '357',
        name: 'Idu Mishmi Textiles',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '509',
        name: 'Arunachal Pradesh Khaw Tai',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '511',
        name: 'Arunachal Pradesh Yak Churpi',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '512',
        name: 'Arunachal Pradesh Tangsa Textile Product',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '544',
        name: 'Arunachal Pradesh Handmade Carpet',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '545',
        name: 'Arunachal Pradesh Wancho Wooden Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '546',
        name: 'Arunachal Pradesh Adi Kekir',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '549',
        name: 'Arunachal Pradesh Apatani Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '550',
        name: 'Arunachal Pradesh Monpa Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '551',
        name: 'Arunachal Pradesh Nyishi Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '552',
        name: 'Arunachal Pradesh Monpa Handmade Paper',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '553',
        name: 'Arunachal Pradesh Adi Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '555',
        name: 'Arunachal Pradesh Galo Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '556',
        name: 'Arunachal Pradesh Adi Apong',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '557',
        name: 'Arunachal Pradesh Dao',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '558',
        name: 'Arunachal Pradesh Angnyat Millet',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '559',
        name: 'Arunachal Pradesh Marua Apo',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '560',
        name: 'Arunachal Pradesh Tai Khamti Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Arunachal Pradesh, Assam',
    items: [
      {
        serial: '554',
        name: 'Arunachal Pradesh Singpho Phalap',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '623',
        name: 'Assam Mishing Handloom Products',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Assam',
    items: [
      {
        serial: '35',
        name: 'Muga silk of Assam',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '101',
        name: 'Assam (orthodox)',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '200',
        name: 'Muga Silk of Assam (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '226',
        name: 'Assam Karbi Anglong Ginger',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '230',
        name: 'Tezpur Litchi',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '287',
        name: 'Joha rice of Assam',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '322',
        name: 'Boka Chaul',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '361',
        name: 'Kaji Nemu',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '362',
        name: 'Chokuwa rice of Assam',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '376',
        name: 'Judima',
        type: 'Manufactured',
        year: '2021–22',
      },
      {
        serial: '432',
        name: 'Gamosa of Assam',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '571',
        name: 'Majuli Mask of Assam',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '572',
        name: 'Assam Majuli Manuscript Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '605',
        name: 'Bodo Dokhona',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '606',
        name: 'Bodo Eri Silk',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '607',
        name: 'Bodo Jwmgra',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '608',
        name: 'Bodo Gamsa',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '609',
        name: 'Bodo Keradapini',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '610',
        name: 'Bodo Thorkha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '611',
        name: 'Bodo Gongar Dunjia',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '612',
        name: 'Bodo Kham',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '613',
        name: 'Bodo Serja',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '614',
        name: 'Bodo Sifung',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '615',
        name: 'Bodo Khardwi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '616',
        name: 'Bodo Gongona',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '617',
        name: 'Bodo Jotha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '618',
        name: 'Assam Jaapi',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '619',
        name: 'Assam Asharikandi Terracotta Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '624',
        name: 'Assam Bihu Dhol',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '625',
        name: 'Assam Pani Meteka Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '626',
        name: 'Sarthebari Metal Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Bihar',
    items: [
      {
        serial: '30',
        name: 'Madhubani paintings',
        type: 'Handicraft',
        year: '2006–07',
      },
      {
        serial: '44',
        name: 'Applique (khatwa) work of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '45',
        name: 'Sujini embroidery work of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '46',
        name: 'Sikki Grass Products of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '178',
        name: 'Bhagalpur silk',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '284',
        name: 'Applique (Khatwa) Work of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '291',
        name: 'Sikki Grass Products of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '292',
        name: 'Sujini Embroidery Work of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '311',
        name: 'Bhagalpuri Zardalu',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '312',
        name: 'Katarni Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '313',
        name: 'Magahi Paan',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '326',
        name: 'Shahi Litchi of Bihar',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '330',
        name: 'Silao Khaja',
        type: 'Food stuff',
        year: '2018–19',
      },
      {
        serial: '386',
        name: 'Manjusha Art',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '421',
        name: 'Mithila Makhana',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '495',
        name: 'Marcha Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Chhattisgarh',
    items: [
      {
        serial: '62',
        name: 'Bastar Dhokra',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '63',
        name: 'Bastar Wooden Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '68',
        name: 'Bastar Iron Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '136',
        name: 'Champa silk saree and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '196',
        name: 'Bastar Dhokra (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '343',
        name: 'Jeeraphool',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '435',
        name: 'Nagri Dubraj',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Germany',
    items: [
      {
        serial: '410',
        name: 'Münchener Bier',
        type: 'Manufactured',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Goa',
    items: [
      {
        serial: '105',
        name: 'Feni',
        type: 'Manufactured',
        year: '2008–09',
      },
      {
        serial: '356',
        name: 'Khola Chilli',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '387',
        name: 'Harmal Chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '394',
        name: 'Myndoli Banana',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '400',
        name: 'Goan Khaje',
        type: 'Food stuff',
        year: '2021–22',
      },
      {
        serial: '492',
        name: 'Agsechi Vayingim (Agassaim Brinjal)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '494',
        name: 'Sat Shiro Bheno',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '497',
        name: 'Goa Mankurad Mango',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '498',
        name: 'Goan Bebinca',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '506',
        name: 'Goa Cashew (Kaju or Caju)',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Gujarat',
    items: [
      {
        serial: '79',
        name: 'Sankheda Furniture',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '80',
        name: 'Agates of Cambay',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '82',
        name: 'Kutch Embroidery',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '111',
        name: 'Tangaliya Shawl',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '141',
        name: 'Surat Zari Craft',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '152',
        name: 'Gir Kesar Mango',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '153',
        name: 'Bhalia Wheat',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '156',
        name: 'Kachchh Shawls',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '194',
        name: 'Patan patola',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '240',
        name: 'Sankheda Furniture (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '241',
        name: 'Kutch Embroidery (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '251',
        name: 'Agates of Cambay (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '273',
        name: 'Jamnagari Bandhani',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '325',
        name: 'RajKot Patola',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '328',
        name: 'Pethapur Printing Blocks',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '385',
        name: 'Pithora',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '455',
        name: 'Mata ni Pachhedi',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '539',
        name: 'Kachchhi Kharek',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '566',
        name: 'Kutch Rogan Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '573',
        name: 'Ambaji White Marble',
        type: 'Natural',
        year: '2023–24',
      },
      {
        serial: '576',
        name: 'Kutch Bandhani',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '593',
        name: 'Gharchola Craft of Gujarat',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '620',
        name: 'Gujarat Suf Embroidery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '628',
        name: 'Ahmedabad Sodagari Block Print',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '629',
        name: 'Surat Sadeli Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '632',
        name: 'Bharuch Sujani Weaving',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '643',
        name: 'Kutch Ajrakh',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Himachal Pradesh',
    items: [
      {
        serial: '14',
        name: 'Kullu Shawl',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '20',
        name: 'Kangra Tea',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '84',
        name: 'Chamba Rumal',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '125',
        name: 'Kinnauri Shawl',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '199',
        name: 'Kullu Shawl (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '214',
        name: 'Kangra Paintings',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '336',
        name: 'Himachali Kala Zeera',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '338',
        name: 'Himachali Chulli Oil',
        type: 'Manufactured',
        year: '2018–19',
      },
      {
        serial: '403',
        name: 'Chamba Chappal',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '405',
        name: 'Lahauli Knitted Socks and Gloves',
        type: 'Handicraft',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Jammu and Kashmir',
    items: [
      {
        serial: '83',
        name: 'Kani Shawl',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '97',
        name: 'Kashmir Pashmina',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '98',
        name: 'Kashmir Sozani Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '160',
        name: 'Kashmir paper machie',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '161',
        name: 'Kashmir Walnut Wood Carving',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '163',
        name: 'Khatamband',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '272',
        name: 'Kashmiri Hand Knotted Carpet',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '366',
        name: 'Kashmir Saffron',
        type: 'Agricultural',
        year: '2020–21',
      },
      {
        serial: '470',
        name: 'Basohli Painting',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '490',
        name: 'Mushqbudji Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '493',
        name: 'Rajouri Chikri Wood Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '503',
        name: 'Bhaderwah Rajmash',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '504',
        name: 'Ramban Sulai Honey',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '507',
        name: 'Basohli Pashmina Woolen Products',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '510',
        name: 'Udhampur Kaladi',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '542',
        name: 'Ramban Anardana',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Jharkhand',
    items: [
      {
        serial: '370',
        name: 'Sohrai – Khovar Painting',
        type: 'Handicraft',
        year: '2020–21',
      },
    ],
  },
  {
    state: 'Karnataka',
    items: [
      {
        serial: '9',
        name: 'Mysore silk',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '11',
        name: 'Mysore Agarbathi',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '15',
        name: 'Bidriware',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '18',
        name: 'Channapatna toys and dolls',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '19',
        name: 'Mysore Rosewood Inlay',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '23',
        name: 'Mysore Sandalwood Oil',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '24',
        name: 'Mysore Sandal soap',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '25',
        name: 'Kasuti embroidery',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '26',
        name: 'Mysore Traditional Paintings',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '27',
        name: 'Coorg orange',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '28',
        name: 'Mysore betel leaf',
        type: 'Agricultural',
        year: '2006–07',
      },
      {
        serial: '29',
        name: 'Nanjanagud Banana',
        type: 'Agricultural',
        year: '2006–07',
      },
      {
        serial: '37',
        name: 'Mysore Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '38',
        name: 'Udupi Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '39',
        name: 'Hadagali Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '43',
        name: 'Ilkal sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '50',
        name: 'Ganjifa Cards of Mysore',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '51',
        name: 'Navalgund Durries',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '52',
        name: 'Karnataka Bronzeware',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '53',
        name: 'Molakalmuru sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '57',
        name: 'Coorg Green Cardamom',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '85',
        name: 'Dharwad Pedha',
        type: 'Food stuff',
        year: '2008–09',
      },
      {
        serial: '113',
        name: 'Devanahalli Pomello',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '114',
        name: 'Appemidi Mango',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '115',
        name: 'Kamalapur Red Banana',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '128',
        name: 'Sandur Lambani Embroidery',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '147',
        name: 'Byadagi chilli',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '157',
        name: 'Udupi Mattu Gulla Brinjal',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '164',
        name: 'Kinhal toys',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '188',
        name: 'Bangalore Blue Grapes',
        type: 'Agricultural',
        year: '2012–13',
      },
      {
        serial: '217',
        name: 'Bangalore Rose Onion',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '242',
        name: 'Karnataka Bronzeware (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '243',
        name: 'Ganjifa Cards of Mysore (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '244',
        name: 'Navalgund Durries (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '252',
        name: 'Guledgudd Khana',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '253',
        name: 'Udupi sarees',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '275',
        name: 'Mysore Silk (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '331',
        name: 'Coorg Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '333',
        name: 'Chikmagalur Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '335',
        name: 'Bababudangiri Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '337',
        name: 'Sirsi Supari',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '353',
        name: 'Gulbarga Tur Dal',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '469',
        name: 'Indi Limbe',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '475',
        name: 'Kari Ishad Mango',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Karnataka, Kerala',
    items: [
      {
        serial: '54',
        name: 'Monsooned Malabar Arabica Coffee',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '55',
        name: 'Monsooned Malabar Robusta Coffee',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Kerala',
    items: [
      {
        serial: '2',
        name: 'Aranmula Kannadi',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '34',
        name: 'Alleppey Coir',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '40',
        name: 'Navara rice',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '41',
        name: 'Palakkadan Matta rice',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '65',
        name: 'Maddalam of Palakkad',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '66',
        name: 'Screw Pine Craft of Kerala',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '73',
        name: 'Brass Broidered Coconut Shell Crafts of Kerala',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '86',
        name: 'Pokkali Rice',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '112',
        name: 'Vazhakulam pineapple',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '117',
        name: 'Cannanore Home Furnishings',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '120',
        name: 'Balaramapuram sarees and fine cotton fabrics',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '126',
        name: 'Kasaragod sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '127',
        name: 'Kuthampully sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '135',
        name: 'Central Travancore Jaggery',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '137',
        name: 'Wayanad Jeerakasala rice',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '138',
        name: 'Wayanad Gandhakasala rice',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '144',
        name: 'Payyannur Pavithra Ring',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '165',
        name: 'Chendamangalam Dhoties and Set Mundu',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '198',
        name: 'Kaipad Rice',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '228',
        name: 'Chengalikodan Nendran Banana',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '254',
        name: 'Kuthampally Dhoties and Set Mundu',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '259',
        name: 'Maddalam of Palakkad (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '260',
        name: 'Brass Broidered Coconut Shell Craft of Kerala (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '261',
        name: 'Screw Pine Craft of Kerala (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '305',
        name: 'Nilambur Teak',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '332',
        name: 'Wayanaad Robusta Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '341',
        name: 'Marayoor Jaggery',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '354',
        name: 'Tirur Betel Leaf',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '383',
        name: 'Kuttiattoor Mango',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '388',
        name: 'Edayur Chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '425',
        name: 'Attappady Aattukombu Avara',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '426',
        name: 'Attappady Thuvara',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '427',
        name: 'Onattukara Ellu',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '428',
        name: 'Kanthalloor Vattavada Veluthulli',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '429',
        name: 'Kodungallur Pottuvellari',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Kerala, Karnataka, Tamil Nadu',
    items: [
      {
        serial: '47',
        name: 'Malabar pepper',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Ladakh',
    items: [
      {
        serial: '431',
        name: 'Ladakh Raktsey Karpo Apricot',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '466',
        name: 'Pashmina Wool of Ladakh',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '472',
        name: 'Ladakh Shingskos',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '484',
        name: 'Ladakh Seabuckthorn',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Madhya Pradesh',
    items: [
      {
        serial: '5',
        name: 'Chanderi sarees',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '77',
        name: 'Leather Toys of Indore',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '78',
        name: 'Bagh Prints of Madhya Pradesh',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '81',
        name: 'Bell Metal Ware of Datia and Tikamgarh',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '172',
        name: 'Maheshwari Saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '197',
        name: 'Bell Metal Ware of Datia and Tikamgarh (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '216',
        name: 'Leather Toys of Indore (Logo)',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '229',
        name: 'Ratlami Sev',
        type: 'Food stuff',
        year: '2014–15',
      },
      {
        serial: '239',
        name: 'Bagh Prints of Madhya Pradesh (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '321',
        name: 'Jhabua Kadaknath Black Chicken Meat',
        type: 'Food stuff',
        year: '2018–19',
      },
      {
        serial: '382',
        name: 'Balaghat Chinnor',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '436',
        name: 'Morena Gajak',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '437',
        name: 'Rewa Sunderja Mango',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '438',
        name: 'Sharbati Gehu',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '439',
        name: 'Gond Painting of Madhya Pradesh',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '456',
        name: 'Wrought Iron Crafts of Dindori',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '457',
        name: 'Ujjain Batik Print',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '458',
        name: 'Gwalior Handmade Carpet',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '459',
        name: 'Waraseoni handloom saree and fabrics',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '460',
        name: 'Jabalpur Stone Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '568',
        name: 'Ratlam Riyawan Lahsun',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Maharashtra',
    items: [
      {
        serial: '6',
        name: 'Solapuri chaddar',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '7',
        name: 'Solapur Terry Towel',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '109',
        name: 'Puneri Pagadi',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '123',
        name: 'Nashik valley wine',
        type: 'Manufactured',
        year: '2010–11',
      },
      {
        serial: '130',
        name: 'Paithani sarees and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '131',
        name: 'Mahabaleshwar Strawberry',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '140',
        name: 'Nashik Grapes',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '209',
        name: 'Kolhapur Jaggery',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '248',
        name: 'Ajara Ghansal Rice',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '249',
        name: 'Mangalwedha Jowar',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '250',
        name: 'Sindhudurg and Ratnagiri Kokum',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '255',
        name: 'Waghya Ghevada',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '256',
        name: 'Navapur Tur Dal',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '257',
        name: 'Vengurla Cashew',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '258',
        name: 'Lasalgaon Onion',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '262',
        name: 'Sangli Raisins',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '265',
        name: 'Beed Custard Apple',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '266',
        name: 'Jalna Sweet Orange',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '268',
        name: 'Waigaon Turmeric',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '269',
        name: 'Purandar Fig',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '270',
        name: 'Jalgaon Bharit Brinjal',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '271',
        name: 'Solapur Pomegranate',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '278',
        name: 'Bhiwapur Chilli',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '279',
        name: 'Ambemohar Rice',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '280',
        name: 'Dahanu Gholvad Chikoo',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '281',
        name: 'Jalgaon Banana',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '282',
        name: 'Marathwada Kesar Mango',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '283',
        name: 'Karvath Kati sarees and fabrics',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '324',
        name: 'Alphonso mango',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '327',
        name: 'Sangli Turmeric',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '424',
        name: 'Alibag White Onion',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '485',
        name: 'Bhandara Chinoor Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '548',
        name: 'Sawantwadi Ganjifa Cards',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '577',
        name: 'Vasmat Haldi (Turmeric)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '578',
        name: 'Nandurbar Amchur',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '579',
        name: 'Nandurbar Mirchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '580',
        name: 'Miraj Tanpura',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '581',
        name: 'Hupari Silver Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '582',
        name: 'Miraj Sitar',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '583',
        name: 'Sawantwadi Wooden Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '589',
        name: 'Panchincholi Tamarind',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '590',
        name: 'Borsuri Tur Dal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '591',
        name: 'Kasti Coriander',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '595',
        name: 'Badlapur Jamun',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '600',
        name: 'Bahadoli Jamun',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '601',
        name: 'Pen Ganesh Idol',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '602',
        name: 'Kunthalgiri Khawa',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '603',
        name: 'Kavdi Maal of Tuljapur',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '604',
        name: 'Dagdi Jowar of Jalna',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Maharashtra, Gujarat',
    items: [
      {
        serial: '208',
        name: 'Warli Painting',
        type: 'Handicraft',
        year: '2013–14',
      },
    ],
  },
  {
    state: 'Maharashtra, Karnataka',
    items: [
      {
        serial: '329',
        name: 'Kolhapuri Chappal',
        type: 'Handicraft',
        year: '2018–19',
      },
    ],
  },
  {
    state: 'Maharashtra, Madhya Pradesh',
    items: [
      {
        serial: '215',
        name: 'Nagpur Orange',
        type: 'Agricultural',
        year: '2013–14',
      },
    ],
  },
  {
    state: 'Manipur',
    items: [
      {
        serial: '211',
        name: 'Shaphee Lanphee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '212',
        name: 'Wangkhei Phee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '213',
        name: 'Moirang Phee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '232',
        name: 'Kachai Lemon',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '402',
        name: 'Tamenglong Orange',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '407',
        name: 'Sirarakhong Hathei chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Manipur, Nagaland',
    items: [
      {
        serial: '364',
        name: 'Chak-Hao',
        type: 'Agricultural',
        year: '2019–20',
      },
    ],
  },
  {
    state: 'Meghalaya',
    items: [
      {
        serial: '231',
        name: 'Khasi Mandarin',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '236',
        name: 'Memong Narang',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '575',
        name: 'Lakadong Turmeric',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '633',
        name: 'Meghalaya Garo Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '634',
        name: 'Meghalaya Lyrnai Pottery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '635',
        name: 'Meghalaya Chubitchi',
        type: 'Manufactured',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Mizoram',
    items: [
      {
        serial: '223',
        name: 'Mizo Chilli',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '347',
        name: 'Pawndum',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '348',
        name: 'Ngotekherh',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '349',
        name: 'Hmaram',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '351',
        name: 'Tawlhlohpuan',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '352',
        name: 'Mizo Puanchei',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '413',
        name: 'Mizo Ginger',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Nagaland',
    items: [
      {
        serial: '99',
        name: 'Naga Mircha',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '220',
        name: 'Naga Tree Tomato',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '301',
        name: 'Chakshesang Shawl',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '408',
        name: 'Naga Cucumber',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Odisha',
    items: [
      {
        serial: '8',
        name: 'Kotpad Handloom fabrics',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '17',
        name: 'Orissa Ikat',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '69',
        name: 'Konark stone carving',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '70',
        name: 'Orissa Pattachitra',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '87',
        name: 'Pipli Applique Work',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '146',
        name: 'Khandua saree and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '168',
        name: 'Gopalpur Tussar Fabrics',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '170',
        name: 'Ganjam Kewda Rooh',
        type: 'Manufactured',
        year: '2011–12',
      },
      {
        serial: '171',
        name: 'Ganjam Kewda Flower',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '173',
        name: 'Dhalapathar Parda & Fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '174',
        name: 'Sambalpuri bandha saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '175',
        name: 'Bomkai saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '176',
        name: 'Habaspuri saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '177',
        name: 'Berhampur Patta (phoda kumbha) saree and joda',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '195',
        name: 'Orissa Pattachitra (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '344',
        name: 'Kandhamal Haladi',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '345',
        name: 'Odisha Rasagola',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '508',
        name: 'Kendrapara Rasabali',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '531',
        name: 'Odisha Khajuri Guda',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '535',
        name: 'Dhenkanal Magji',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '536',
        name: 'Similipal Kai Chutney of Odisha',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '537',
        name: 'Nayagarh Kanteimundi Brinjal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '541',
        name: 'Kapadaganda: Dungaria Kondh Embroidery Shawl',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '543',
        name: 'Koraput Kalajeera Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '547',
        name: 'Painting of Lanjia Saura, Odisha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '567',
        name: 'Cuttack Rupa Tarakasi',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Pondicherry',
    items: [
      {
        serial: '154',
        name: 'Villianur Terracotta Works',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '155',
        name: 'Tirukanur Papier Mache Craft',
        type: 'Handicraft',
        year: '2011–12',
      },
    ],
  },
  {
    state: 'Portugal',
    items: [
      {
        serial: '166',
        name: 'Porto',
        type: 'Manufactured',
        year: '2011–12',
      },
      {
        serial: '167',
        name: 'Douro',
        type: 'Manufactured',
        year: '2011–12',
      },
    ],
  },
  {
    state: 'Punjab, Haryana, Himachal Pradesh, Delhi, Uttarkhand, Uttar Pradesh, Jammu and Kashmir',
    items: [
      {
        serial: '238',
        name: 'Basmati',
        type: 'Agricultural',
        year: '2015–16',
      },
    ],
  },
  {
    state: 'Punjab, Haryana, Rajasthan',
    items: [
      {
        serial: '145',
        name: 'Phulkari',
        type: 'Handicraft',
        year: '2010–11',
      },
    ],
  },
  {
    state: 'Rajasthan',
    items: [
      {
        serial: '10',
        name: 'Kota Doria',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '74',
        name: 'Blue Pottery of Jaipur',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '75',
        name: 'Molela Clay Work',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '76',
        name: 'Kathputlis of Rajasthan',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '119',
        name: 'Sanganeri hand block printing',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '121',
        name: 'Bikaneri Bhujia',
        type: 'Food stuff',
        year: '2010–11',
      },
      {
        serial: '139',
        name: 'Kota Doria (logo)',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '150',
        name: 'Bagru Hand Block Print',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '210',
        name: 'Thewa Art Work',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '233',
        name: 'Makrana Marble',
        type: 'Natural Goods',
        year: '2014–15',
      },
      {
        serial: '285',
        name: 'Molela Clay Work of Rajasthan (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '293',
        name: 'Blue Pottery of Jaipur (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '294',
        name: 'Kathputlis of Rajasthan (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '307',
        name: 'Pokaran Pottery',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '372',
        name: 'Sojat Mehndi',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '488',
        name: 'Nathdwara Pichhwai Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '499',
        name: 'Udaipur Koftgari Metal Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '500',
        name: 'Bikaner Kashidakari Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '501',
        name: 'Jodhpur Bandhej Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '502',
        name: 'Bikaner Usta Kala Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Sikkim',
    items: [
      {
        serial: '222',
        name: 'Sikkim Large Cardamom',
        type: 'Agricultural',
        year: '2014–15',
      },
    ],
  },
  {
    state: 'Sikkim, West Bengal',
    items: [
      {
        serial: '414',
        name: 'Dalle Khursani',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Tamil Nadu',
    items: [
      {
        serial: '4',
        name: 'Salem fabric',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '12',
        name: 'Kancheepuram Silk',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '13',
        name: 'Bhavani Jamakkalam',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '16',
        name: 'Madurai Sungudi',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '21',
        name: 'Coimbatore Wet Grinder',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '32',
        name: 'Thanjavur Paintings',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '36',
        name: 'Temple Jewellery of Nagercoil',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '42',
        name: 'Thanjavur Art Plate',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '58',
        name: 'East India Leather',
        type: 'Manufactured',
        year: '2007–08',
      },
      {
        serial: '59',
        name: 'Salem Venpattu',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '60',
        name: 'Kovai Kora cotton sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '61',
        name: 'Arani Silk',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '67',
        name: 'Swamimalai Bronze Icons',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '72',
        name: 'Eathomozhy Tall Coconut',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '89',
        name: 'Thanjavur Doll',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '100',
        name: 'Nilgiri (orthodox)',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '103',
        name: 'Virupakshi Hill Banana',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '104',
        name: 'Sirumalai Hill Banana',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '180',
        name: 'Madurai Malli',
        type: 'Agricultural',
        year: '2012–13',
      },
      {
        serial: '182',
        name: 'Pattamadai Mat',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '183',
        name: 'Nachiarkoil kuthuvilakku',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '184',
        name: 'Chettinad Kottan',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '186',
        name: 'Toda Embroidery',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '187',
        name: 'Thanjavur Veenai',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '245',
        name: 'Thanjavur Art Plate (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '246',
        name: 'Swamimalai Bronze Icons (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '247',
        name: 'Temple Jewellery of Nagercoil (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '302',
        name: 'Mahabalipuram Stone Sculpture',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '340',
        name: 'Erode Manjal',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '342',
        name: 'Thirubuvanam silk sarees',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '346',
        name: 'Kodaikanal Malai Poondu',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '350',
        name: 'Palani Panchamirtham',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '358',
        name: 'Dindigul Locks',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '359',
        name: 'Kandangi saree',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '360',
        name: 'Srivilliputtur Palkova',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '363',
        name: 'Kovilpatti Kadalai Mittai',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '367',
        name: 'Thanjavur Netti Works',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '368',
        name: 'Arumbavur Wood Carvings',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '373',
        name: 'Karuppur Kalamkari Paintings',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '374',
        name: 'Kallakurichi Wood Carving',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '406',
        name: 'Kanniyakumari Clove',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '420',
        name: 'Narasinghapettai Nagaswaram',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '441',
        name: 'Ramnathapuram Mundu Chilli',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '442',
        name: 'Vellore Spiny Brinjal',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '443',
        name: 'Myladi Stone Carvings',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '444',
        name: 'Manapparai Murukku',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '445',
        name: 'Ooty Varkey',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '446',
        name: 'Manamadurai Pottery',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '447',
        name: 'Thaikkal Rattan Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '461',
        name: 'Salem Sago',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '464',
        name: 'Authoor Vetrilai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '468',
        name: 'Cumbum Panneer Thratchai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '471',
        name: 'Negamam cotton saree',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '473',
        name: 'Sholavandan Vetrilai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '474',
        name: 'Marthandam Honey',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '486',
        name: 'Jaderi Namakatti',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '489',
        name: 'Kanyakumari Matti Banana',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '491',
        name: 'Chedibutta saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '505',
        name: 'Udangudi Panangkarupatti',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Tamil Nadu, Kerala',
    items: [
      {
        serial: '56',
        name: 'Alleppey Green Cardamom',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Telangana',
    items: [
      {
        serial: '3',
        name: 'Pochampally sari',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '33',
        name: 'Silver Filigree of Karimnagar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '64',
        name: 'Nirmal toys and craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '91',
        name: 'Nirmal furniture',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '92',
        name: 'Nirmal paintings',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '124',
        name: 'Gadwal sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '132',
        name: 'Hyderabad Haleem',
        type: 'Food stuff',
        year: '2010–11',
      },
      {
        serial: '142',
        name: 'Cheriyal Paintings',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '143',
        name: 'Pembarthi Metal Craft',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '169',
        name: 'Siddipet Gollabama',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '185',
        name: 'Narayanpet handloom sarees',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '296',
        name: 'Pochampally Ikat (Logo)',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '308',
        name: 'Adilabad Dokra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '309',
        name: 'Warangal Durries',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '369',
        name: 'Telia Rumal',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '430',
        name: 'Tandur Redgram',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '570',
        name: 'Hyderabad Lac Bangles',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Telangana, Andhra Pradesh',
    items: [
      {
        serial: '295',
        name: 'Banaganapalle Mangoes',
        type: 'Agricultural',
        year: '2017–18',
      },
    ],
  },
  {
    state: 'Tripura',
    items: [
      {
        serial: '227',
        name: 'Tripura Queen Pineapple',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '569',
        name: 'Tripura Risa Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '630',
        name: 'Tripura Pachra-Rignai',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '631',
        name: 'Tripura Matabari Peda',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'United States of America',
    items: [
      {
        serial: '134',
        name: 'Napa Valley',
        type: 'Manufactured',
        year: '2010–11',
      },
    ],
  },
  {
    state: 'Uttar Pradesh',
    items: [
      {
        serial: '48',
        name: 'Allahabad Surkha guava',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '102',
        name: 'Lucknow Chikan Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '108',
        name: 'Mango Malihabadi Dusseheri',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '110',
        name: 'Banaras brocades and sarees',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '129',
        name: 'Hand Made Carpet of Bhadohi',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '189',
        name: 'Agra Durrie',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '190',
        name: 'Farrukhabad Prints',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '191',
        name: 'Lucknow Zardozi',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '192',
        name: 'Banaras brocades and sarees (logo)',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '193',
        name: 'Kalanamak Rice',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '202',
        name: 'Firozabad Glass',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '203',
        name: 'Kannauj Perfume',
        type: 'Manufactured',
        year: '2013–14',
      },
      {
        serial: '204',
        name: 'Kanpur Saddlery',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '205',
        name: 'Moradabad Metal Craft',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '206',
        name: 'Saharanpur Wood Craft',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '218',
        name: 'Meerut Scissors',
        type: 'Manufactured',
        year: '2014–15',
      },
      {
        serial: '219',
        name: 'Khurja Pottery',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '225',
        name: 'Banaras Gulabi Meenakari Craft',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '234',
        name: 'Varanasi Wooden Lacquerware and Toys',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '235',
        name: 'Mirzapur Handmade Dari',
        type: 'Handicraft',
        year: '2014–2015',
      },
      {
        serial: '237',
        name: 'Nizamabad Black Pottery',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '264',
        name: 'Banaras Metal Repouse Craft',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '276',
        name: 'Varanasi Glass beads',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '314',
        name: 'Ghazipur Wall-hanging',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '315',
        name: 'Varanasi Soft Stone Jali Work',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '339',
        name: 'Chunar Balua Patthar',
        type: 'Natural',
        year: '2018–19',
      },
      {
        serial: '365',
        name: 'Gorakhpur Terracotta',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '371',
        name: 'Chunar Glaze Pottery',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '395',
        name: 'Banaras Zardozi',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '396',
        name: 'Mirzapur Pital Bartan',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '397',
        name: 'Banaras Wood Carving',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '398',
        name: 'Banaras Hand Block Print',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '401',
        name: 'Rataul Mango',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '404',
        name: 'Mau saree',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '440',
        name: 'Adamchini Chawal',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '448',
        name: 'Aligarh Tala',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '449',
        name: 'Bakhira Brassware',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '450',
        name: 'Banda Shazar Patthar craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '451',
        name: 'Nagina Wood Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '452',
        name: 'Pratapgarh Aonla',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '453',
        name: 'Hathras Hing',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '462',
        name: 'Banaras Langda Aam',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '463',
        name: 'Ramnagar Bhanta',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '465',
        name: 'Muzaffarnagar Gur',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '467',
        name: 'Banaras Pan (Betel Leaf)',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '476',
        name: 'Mahoba Gaura Patthar Hastashlip',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '477',
        name: 'Mainpuri Tarkashi',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '478',
        name: 'Sambhal Horn Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '479',
        name: 'Amroha Dholak',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '480',
        name: 'Baghpat Home Furnishings',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '481',
        name: 'Barabanki Handloom Product',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '482',
        name: 'Kalpi Handmade Paper',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '487',
        name: 'Agra Leather Footwear',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '496',
        name: 'Jalesar Dhatu Shilp',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '574',
        name: 'Patchwork of Rampur',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '584',
        name: 'Mathura Sanjhi Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '586',
        name: 'Banaras Tabla',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '587',
        name: 'Banaras Lal Bharwamirch (Red Pickle Chilli)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '588',
        name: 'Pilibhit Bansuri',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '592',
        name: 'Chiraigaon Karonda of Varanasi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '594',
        name: 'Banaras Lal Peda',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '596',
        name: 'Banaras Shehnai',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '597',
        name: 'Sambhal Bone Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '598',
        name: 'Moonj Craft of Uttar Pradesh',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '599',
        name: 'Chitrakoot Wooden Craft and Toys',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '621',
        name: 'Jaunpur Imarti',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '622',
        name: 'Banaras Thandai',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '627',
        name: 'Banaras Mural Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '637',
        name: 'Pilkhuwa Hand Block Print',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '638',
        name: 'Banaras Metal Casting Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '639',
        name: 'Bareilly Cane and Bamboo',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '640',
        name: 'Tharu Embroidery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '641',
        name: 'Bareilly Zari Zardoji',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '642',
        name: 'Banaras Tirangi Barfi',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Uttar Pradesh, Madhya Pradesh',
    items: [
      {
        serial: '411',
        name: 'Mahoba Desawari Pan',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '585',
        name: 'Bundelkhand Kathiya Gehu',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Uttarakhand',
    items: [
      {
        serial: '267',
        name: 'Uttarakhand Tejpat',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '375',
        name: 'Bhotia Dann of Uttarakhand',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '389',
        name: 'Uttarakhand Aipan',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '390',
        name: 'Munsyari Razma',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '391',
        name: 'Uttarakhand Ringal Craft',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '392',
        name: 'Uttarakhand Tamta Product',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '393',
        name: 'Uttarakhand Thulma',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '399',
        name: 'Kumaon Chyura Oil',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '513',
        name: 'Uttarakhand Berinag Tea',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '514',
        name: 'Uttarakhand Bichhu Buti Fabrics',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '515',
        name: 'Uttarakhand Mandua',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '516',
        name: 'Uttarakhand Jhangora',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '517',
        name: 'Uttarakhand Gahat',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '518',
        name: 'Uttarakhand Lal Chawal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '519',
        name: 'Uttarakhand Kala Bhat',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '520',
        name: 'Uttarakhand Malta Fruit',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '521',
        name: 'Uttarakhand Chaulai',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '522',
        name: 'Almora Lakhori Mirchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '523',
        name: 'Uttarakhand Buransh',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '524',
        name: 'Uttarakhand Pahari Toor Dal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '525',
        name: 'Nainital Mombatti',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '526',
        name: 'Rangwali Pichhoda of Kumaon',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '527',
        name: 'Ramnagar Nainital Litchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '528',
        name: 'Ramgarh Nainital Aadu',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '529',
        name: 'Chamoli Wooden Ramman Mask',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '530',
        name: 'Uttarakhand Likhai',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'West Bengal',
    items: [
      {
        serial: '1',
        name: 'Darjeeling Tea',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '49',
        name: 'Nakshi Kantha',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '90',
        name: 'Santiniketan Leather Goods',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '94',
        name: 'Malda Laxman Bhog mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '95',
        name: 'Malda Khirsapati (Himsagar) mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '96',
        name: 'Malda Fazli mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '116',
        name: 'Santipore saree',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '158',
        name: 'Baluchari Saree',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '159',
        name: 'Dhaniakhali Saree',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '224',
        name: 'Joynagar Moa',
        type: 'Food stuff',
        year: '2014–15',
      },
      {
        serial: '289',
        name: 'Bardhaman Sitabhog',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '290',
        name: 'Bardhaman Mihidana',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '297',
        name: 'Gobindobhog Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '300',
        name: 'Tulaipanji Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '303',
        name: 'Banglar Rasogolla',
        type: 'Food stuff',
        year: '2017–18',
      },
      {
        serial: '306',
        name: 'Bankura Panchmura Terracotta Craft',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '316',
        name: 'Bengal Dokra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '317',
        name: 'Bengal Patachitra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '318',
        name: 'Purulia Chau Mask',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '319',
        name: 'Wooden Mask of Kushmandi',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '320',
        name: 'Madur kathi',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '532',
        name: 'Tangail saree of Bengal',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '533',
        name: 'Garad saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '534',
        name: 'Korial saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '538',
        name: 'Kalonunia Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '540',
        name: 'Sundarban Honey',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '564',
        name: 'Banglar Muslin',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
] satisfies readonly GeographicalIndicationStateGroup[]

export const geographicalIndicationTitleLine =
  'Geographical Indications in India (645)' as const
