export const polityQuiz = {
  quizzes: {
    'quiz-1': [
      {
        question: 'The Indian Constitution has established _______',
        options: [
          'Dual judicial system',
          'Independent judicial system',
          'Partial judicial system',
          'Plural judicial system',
        ],
        correct: 1,
        explanation: 'The Indian Constitution has established Independent judicial system.',
      },
      {
        question:
          'During the framing of the Indian Constitution, the Constituent Assembly held a total of eleven sessions, with sittings spread over how many days?',
        options: ['165', '175', '185', '195'],
        correct: 0,
        explanation: '165 days is the correct answer.',
      },
      {
        question: 'Who among the following, while praising the amnding feature of the Indian Constitution said that "This variety in the aminding process is wise but is rarely found"',
        options: ['Granville Austin', 'HM Seervai', 'Ivor Jennings', 'KC Wheare'],
        correct: 3,
        explanation: 'KC Wheare is the correct answer.',
      },
      {
        question: 'When was the "The Objective Resolution" moved by Jawaharlal Nehru?',
        options: ['13.12.1946', '17.11.1946', '15.08.1947', '16.11.194'],
        correct: 0,
        explanation: 'The "The Objective Resolution" was moved by Jawaharlal Nehru on 13th December 1946.',
      },
      {
        question: 'Who among the following persnalities was appointed as the legal advisor of the Constituent Assembly that drafted the documentof the Constitution of India?',
        options: ['BN Rau', 'BR Ambedkar', 'HVR Iyengar', 'SN Mukherjee'],
        correct: 0,
        explanation: 'BN Rau was appointed as the legal advisor of the Constituent Assembly that drafted the documentof the Constitution of India.',
      },
      {
        question: 'The original Constitution of India was handwritten in English by whom?',
        options: ['HVR Iyengar', 'Prem Behari Narayan Raizada', 'SN Mukherjee', 'Vasant Krishan Vaidya'],
        correct: 1,
        explanation: 'Prem Behari Narayan Raizada handwritten the original Constitution of India in English in italic script.',
      },
      {
        question: 'Who among the following wrote in calligraphic style the Hindi version of the original Constitution of India?',
        options: ['HVR Iyengar', 'Prem Behari Narayan Raizada', 'SN Mukherjee', 'Vasant Krishan Vaidya'],
        correct: 3,
        explanation: 'Vasant Krishan Vaidya wrote in calligraphic style the Hindi version of the original Constitution of India.',
      },
      {
        question: 'The structural part of the Indian Constitution is, to a large extent, derived from the act of _______',
        options: ['The Government of India Act, 1935', 'The Government of India Act, 1919', 'The Government of India Act, 1909', 'The Government of India Act, 1926'],
        correct: 0,
        explanation: 'The structural part of the Indian Constitution is, to a large extent, derived from the act of The Government of India Act, 1935.',
      },
      {
        question: 'How many female members were part of the Constituent Assembly that framed the Constitution of India?',
        options: ['12', '13', '14', '15'],
        correct: 3,
        explanation: '15 female members were part of the Constituent Assembly that framed the Constitution of India.',
      },
      {
        question: 'Who was the chairman of the House Committee of the Constituent Assembly of India?',
        options: ['AV Thakkar', 'B Pattabhi Sitaramayya', 'JB Kripalani', 'KM Munshi'],
        correct: 1,
        explanation: 'B Pattabhi Sitaramayya was the chairman of the House Committee of the Constituent Assembly of India.',
      },
      {
        question: 'The total membership of the Constituent Assembly was 389, of which _______ were representatives of the princely states',
        options: ['84', '93', '102', '109'],
        correct: 1,
        explanation: '93 representatives of the princely states were part of the Constituent Assembly.',
      },
      {
        question: 'When was the first meeting of the Constituent Assembly of India held?',
        options: ['09.12.1946', '15.08.1947', '26.11.1949', '26.01.1950'],
        correct: 0,
        explanation: 'The first meeting of the Constituent Assembly of India was held on 9th December 1946.',
      },
      {
        question: 'Who was the President of the Constituent Assembly of India?',
        options: ['Rajendra Prasad', 'Sarvepalli Radhakrishnan', 'V.V. Giri', 'Zakir Husain'],
        correct: 0,
        explanation: 'Rajendra Prasad was the President of the Constituent Assembly of India.',
      },
      {
        question: 'Which plan led to the formation of the Constituent Assembly of India?',
        options: ['August Plan', 'Cabinet Mission Plan', 'Cripps Mission Plan', 'Mountbatten Plan'],
        correct: 1,
        explanation: 'Cabinet Mission Plan led to the formation of the Constituent Assembly of India.',
      },
      {
        question: 'How many members were originally in the Constituent Assembly of India?',
        options: ['299', '352', '389', '401'],
        correct: 2,
        explanation: '389 members were originally in the Constituent Assembly of India.',
      },
      {
        question: 'Which part of the Constitution of India deals with the Directive Principles of State Policy?',
        options: ['Part III', 'Part IV', 'Part II', 'Part V'],
        correct: 1,
        explanation: 'Part IV deals with the Directive Principles of State Policy. Article 38 to 51 deals with the Directive Principles of State Policy.',
      },
      {
        question: 'Fundamental Rights are in which part of the Constitution of India?',
        options: ['Part III', 'Part IV', 'Part II', 'Part V'],
        correct: 0,
        explanation: 'Fundamental Rights are in Part III (Articles 12–35).',
      },
      {
        question: 'Which part of the Constitution of India deals with the Union Government',
        options: ['Part V', 'Part VI', 'Part VII', 'Part VIII'],
        correct: 0,
        explanation: 'Part V deals with the Union Government. Article 52 to 151 deals with the Union Government.',
      },
      {
        question: 'Emergency provisions are contained in which part of the Constitution of India?',
        options: ['Part XVI', 'Part XVII', 'Part XVIII', 'Part XIX'],
        correct: 2,
        explanation: 'Emergency provisions are contained in Part XVIII (Articles 352 to 360).',
      },
      {
        question: 'Which part of the Constitution of India deals with the Panchayats',
        options: ['Part IX', 'Part X', 'Part XI', 'Part XII'],
        correct: 0,
        explanation: 'Part IX deals with the Panchayats. Article 243 to 243G deals with the Panchayats.',
      },
      {
        question: 'Which Schedule of the Constitution of India contains the languages recognized by the Constitution of India?',
        options: ['Schedule VI', 'Schedule VII', 'Schedule VIII', 'Schedule IX'],
        correct: 2,
        explanation: 'Schedule VIII contains the languages recognized by the Constitution of India.',
      },
      {
        question: 'Which Schedule of the Constitution of India deals with the allocation of seats in the Rajya Sabha',
        options: ['Schedule III', 'Schedule IV', 'Schedule V', 'Schedule VI'],
        correct: 1,
        explanation: 'Schedule IV deals with the allocation of seats in the Rajya Sabha.',
      },
      {
        question: 'The Tenth Schedule of the Constitution of India deals with the _______',
        options: ['Anti-defection law', 'Language', 'Oaths and Affirmations', 'National Integration'],
        correct: 0,
        explanation: 'The Tenth Schedule of the Constitution of India deals with the Anti-defection law.',
      },
      {
        question: 'Which Schedule of the Constitution of India contains provisions for administration of tribal areas in Assam, Meghalaya, Tripura and Mizoram?',
        options: ['Schedule V', 'Schedule VI', 'Schedule VII', 'Schedule VIII'],
        correct: 1,
        explanation: 'Schedule VI contains provisions for administration of tribal areas in Assam, Meghalaya, Tripura and Mizoram.',
      },
      {
        question: '',
        options: ['', '', '', ''],
        correct: 0,
        explanation: '',
      },
    ],
    'quiz-2': [
      {
        question: 'Which article has a similar provision to that of Article 32 and deals with writ jurisdiction?',
        options: [
          'Article 226',
          'Article 227',
          'Article 228',
          'Article 229',
        ],
        correct: 0,
        explanation:
          'Article 226 has a similar provision to that of Article 32 and deals with writ jurisdiction.',
      },
      {
        question:
          'Right of prisoner to speedy trial will be categorised in which of the folowing Fundamental Rights?',
        options: [
          'Right against Exploitation',
          'Right to Equality',
          'Right to Constitutional Remedies',
          'Right to Life and Liberty',
        ],
        correct: 3,
        explanation: 'Right to Life and Liberty is the correct answer.',
      },
      {
        question: 'Which Article of the Indian Constitution prohibits of any religious instruction in the educational istitutions maintained by the Union or by a State or by a local authority?',
        options: [
          'Article 28',
          'Article 29',
          'Article 30',
          'Article 31',
        ],
        correct: 0,
        explanation: 'Article 28 of the Indian Constitution prohibits of any religious instruction in the educational istitutions maintained by the Union or by a State or by a local authority.',
      },
      {
        question: 'Which Article of the Indian Constitution deals with the Right to Constitutional Remedies?',
        options: [
          'Article 32',
          'Article 33',
          'Article 34',
          'Article 35',
        ],
        correct: 0,
        explanation: 'Article 32 deals with the Right to Constitutional Remedies.',
      },
      {
        question: 'Which of the following Articles of the Indian Constitution CANNOT be suspended even during an emergency declared on the grounds of external aggression or internal disturbance?',
        options: ['Articles 14 and 16', 'Articles 15 and 17', 'Articles 20 and 21', 'Articles 30 and 32'],
        correct: 2,
        explanation: 'Articles 20 and 21 cannot be suspended even during an emergency declared on the grounds of external aggression or internal disturbance.',
      },
      {
        question: 'If a 12-year old is found to be working in a factory manufacturing carpets, which of the following Articles of the Indian Constitution will be violated?',
        options: ['Article 23', 'Article 24', 'Article 25', 'Article 26'],
        correct: 1,
        explanation: 'Article 24 deals with the Right to Freedom of the Press. Article 23 prohibits the employment of children in factories and mines.',
      },
      {
        question: 'In which part of the Constitution of India will you find the six broad categories of fundamental rights?',
        options: ['Part III', 'Part IV', 'Part II', 'Part V'],
        correct: 0,
        explanation: 'Part III (Articles 12–35) contains the six broad categories of fundamental rights.',
      },
      {
        question: 'Writ of Mandamus is a fundamental right classified under which of the following categories?',
        options: ['Cultural and educational rights', 'Constitutional remedies', 'the right to freedom of religion', 'the right to equality'],
        correct: 1,
        explanation: 'Writ of Mandamus is a fundamental right classified under Constitutional remedies.',
      },
      {
        question: 'Which of the following Articles of the Indian Constitution prohibits traffic in human beings and forced labour?',
        options: ['Article 23', 'Article 24', 'Article 25', 'Article 26'],
        correct: 0,
        explanation: 'Article 23 prohibits traffic in human beings and forced labour.',
      },
      {
        question: 'Which clause of Article 20 incorporates the doctrine of double jeopardy?',
        options: ['Clause (1)', 'Clause (2)', 'Clause (3)', 'Clause (4)'],
        correct: 1,
        explanation: 'Clause (2) of Article 20 incorporates the doctrine of double jeopardy.',
      },
      {
        question: '_______ has called the Right to Constitutional Remedy as the "Soul of the Constitution"',
        options: ['Bal Gangadhar Tilak', 'Dr. BR Ambedkar', 'Jawaharlal Nehru', 'Lala Lajpat Rai'],
        correct: 1,
        explanation: 'Dr. BR Ambedkar has called the Right to Constitutional Remedy as the "Soul of the Constitution".',
      },
      {
        question: '__________ is issued to prevent an inferior court or tribunal from exceeding its jurisdiction, which is not legally vested, or acting without jurisdiction or acting against the principles of natural justice.',
        options: ['Writ of Prohibition', 'Writ of Mandamus', 'Writ of Habeas Corpus', 'Writ of Quo Warranto'],
        correct: 0,
        explanation: 'Writ of Prohibition is issued to prevent an inferior court or tribunal from exceeding its jurisdiction, which is not legally vested, or acting without jurisdiction or acting against the principles of natural justice.',
      },
      {
        question: 'Which of the following Fundamental Rights is available for Indians as well as foreigners?',
        options: ['Right to protection of language, script and culture of minorities', 'Equality of opportunity in matters of public employment', 'Right to minorities establish and administer educational institutions', 'Right to elementary education'],
        correct: 3,
        explanation: 'Right to elementary education is available for Indians as well as foreigners.',
      },
      {
        question: 'Which writ literally means "what is your authority to do this?"',
        options: ['Quo Warranto', 'Prohibition', 'Mandamus', 'Habeas Corpus'],
        correct: 0,
        explanation: 'Quo Warranto literally means "what is your authority to do this?"',
      },
      {
        question: 'Citizens are NOT discriminated against on the basis of religion, caste, or sex because of _______',
        options: ['Right to Equality', 'Right to Freedom of Religion', 'Right to Freedom of Speech', 'Right to Freedom of the Press'],
        correct: 0,
        explanation: 'Right to Equality is not discriminated against on the basis of religion, caste, or sex.',
      },
      {
        question: 'How many Fundamental Rights were initially provided in the Constitution of India?',
        options: ['5', '6', '7', '8'],
        correct: 2,
        explanation: '7 Fundamental Rights were initially provided in the Constitution of India.',
      },
      {
        question: '__________ of the Constitution of India has provision for legal enforcement of Fundamental Rights?',
        options: ['Article 32', 'Article 33', 'Article 34', 'Article 35'],
        correct: 0,
        explanation: 'Article 32 has provision for legal enforcement of Fundamental Rights.',
      },
      {
        question: 'Which of the following is enforceable by the Indian Constitution?',
        options: ['Directive Principles of State Policy', 'Fundamental Rights', 'Fundamental Duties', 'Preamble'],
        correct: 1,
        explanation: 'Fundamental Rights are enforceable by the Indian Constitution.',
      },
      {
        question: 'The Preamble of the Constitution of India describes India as a "_______"',
        options: ['an atheist state', 'a unitary state', 'a secular state', 'a federal state'],
        correct: 2,
        explanation: 'The Preamble of the Constitution of India describes India as a "a secular state".',
      },
      {
        question: 'Which of the following word sequences is correct as per the Preamble of the Constitution of India?',
        options: ['Sovereign, socialist, secular, democratic, republic', 'Secular, democratic, socialist, sovereign', 'Sovereign, secular, socialist, democratic, republic', 'Socialist, secular, democratic,republic, sovereign'],
        correct: 0,
        explanation: 'Sovereign, socialist, secular, democratic, republic is the correct word sequence as per the Preamble of the Constitution of India.',
      },
      {
        question: 'When was the Preamble of the Constitution of India amended?',
        options: ['1976', '1977', '1978', '1979'],
        correct: 0,
        explanation: 'The Preamble of the Constitution of India was amended in 1976.',
      },
      {
        question: 'Who called the Preamble of the Constitution of India as the "The Political Horoscope of our Constitution"?',
        options: ['Dr. KM Munshi', 'M. Hidayatullah', 'Sir Alladi Krishnaswami Aiyar', 'Sir Ernest Barker'],
        correct: 0,
        explanation: 'Dr. KM Munshi called the Preamble of the Constitution of India as the "The Political Horoscope of our Constitution".',
      },
      {
        question: 'From which of the following Constitutions is the idea of "Charter of Fundamental Rights" adapted in the Constitution of India?',
        options: ['Brazil', 'France', 'Spain', 'USA'],
        correct: 3,
        explanation: 'The idea of "Charter of Fundamental Rights" was adapted from the Constitution of the United States of America.',
      },
      {
        question: 'Which of the following words is not found in the original Preamble of the Constitution of India?',
        options: ['Sovereign', 'Socialist', 'Secular', 'Both B and C'],
        correct: 3,
        explanation: 'Both B and C are found in the original Preamble of the Constitution of India.',
      },
      {
        question: 'The Preamble of the Constitution of India declares India to be a "_______"',
        options: ['A federal state', 'A unitary state', 'A Sovereign Socialist Secular Democratic Republic', 'A monarchy'],
        correct: 2,
        explanation: 'The Preamble of the Constitution of India declares India to be a "A Sovereign Socialist Secular Democratic Republic".',
      },
      {
        question: 'Which amendment added the words "Socialist" and "Secular" to the Preamble of the Constitution of India?',
        options: ['42nd Amendment', '43rd Amendment', '44th Amendment', '45th Amendment'],
        correct: 0,
        explanation: '42nd Amendment added the words "Socialist" and "Secular" to the Preamble of the Constitution of India in 1976.',
      },
      {
        question: 'Who described the Preamble as the "Identity Card of the Constitution"?',
        options: ['Dr. BR Ambedkar', 'Dr. Rajendra Prasad', 'Jawaharlal Nehru', 'Nani Palkhivala'],
        correct: 3,
        explanation: 'Nani Palkhivala described the Preamble as the "Identity Card of the Constitution".',
      },
      {
        question: 'The idea of the Preamble of the Constitution of India was inspired by the Constitution of the ________',
        options: ['United States of America', 'United Kingdom', 'France', 'Germany'],
        correct: 0,
        explanation: 'The idea of the Preamble of the Constitution of India was inspired by the Constitution of the United States of America.',
      },
      {
        question: 'The Preamble is part of the Constitution as per the verdict in which case?',
        options: ['A.K Gopalan vs State of Madras', 'Golaknath vs State of Punjab', 'Kesavananda Bharti vs State of Kerala', 'M.C Mehta vs Union of India'],
        correct: 2,
        explanation: 'The Preamble is part of the Constitution as per the verdict in Kesavananda Bharti vs State of Kerala.',
      },
      {
        question: 'Which of the following best describes the nature of the Preamble of the Constitution of India?',
        options: ['It is enforceable by the courts', 'It is not a part of the Constitution', 'It is just a decorative element', 'It embodies the spirit of the Constitution'],
        correct: 3,
        explanation: 'It embodies the spirit of the Constitution.',
      },
      {
        question: '',
        options: ['', '', '', ''],
        correct: 0,
        explanation: '',
      },
      
    ],
    'quiz-3': [
      {
        question: 'Which of the following provisions of the Indian Constitution has NOT been taken from the British Constitution?',
        options: [
          'Bicameral system',
          'Fundamental Rights',
          'Legislative process',
          'Rule of Law',
        ],
        correct: 1,
        explanation: 'Fundamental Rights has not been taken from the British Constitution.',
      },
      {
        question: 'The concurrent list in the Constitution of India was adopted from _______',
        options: ['Australia', 'Canada', 'New Zealand', 'South Africa'],
        correct: 0,
        explanation: 'The concurrent list in the Constitution of India was adopted from Australia.',
      },
      {
        question: 'Which of the following provisions of the Indian Constitution has been taken from the constitution of Canada?',
        options: ['Advisory jurisdiction of the Supreme Court', 'Concept of Republic', 'Concept of Concurrent List', 'Independent Judiciary'],
        correct: 0,
        explanation: 'Advisory jurisdiction of the Supreme Court has been taken from the constitution of Canada.',
      },
      {
        question: 'Which of the following provisions of the Indian Constitution has NOT been taken from the constitution of Canada?',
        options: ['Advisory jurisdiction of the Supreme Court', 'Appointment of the Governor of the state by the Centre', 'Concept of Concurrent List', 'Union with a strong center'],
        correct: 2,
        explanation: 'Concept of Concurrent List has NOT been taken from the constitution of Canada.',
      },
      {
        question: 'Which of the following provisions and the constitutions of different countries from which they have been adopted in the Indian Constitution has been incorectly paired?',
        options: ['Charted of Fundamental Rights - US Constitution', 'Directive Principles of State Policy - Irish Constitution', 'Principles of Liberty, Equality and Fraternity - Canadian Constitution', 'The idea of the rule of law - UK Constitution'],
        correct: 2,
        explanation: 'Principles of Liberty, Equality and Fraternity - Canadian Constitution has been incorrectly paired.',
      },
      {
        question: 'Which of the following features in the Indian Constitution was derived from the Union Soviet Socialist Republic (USSR)?',
        options: ['Concurrent List', 'Fundamental Rights', 'Five year plan', 'Preamble'],
        correct: 2,
        explanation: 'Five year plan was derived from the Union Soviet Socialist Republic (USSR).',
      },
      {
        question: 'In the Indian Constitution, the principle of liberty is borrowed from the which of the following countries?',
        options: ['United States of America', 'United Kingdom', 'France', 'Germany'],
        correct: 2,
        explanation: 'The principle of liberty is borrowed from the France.',
      },
      {
        question: 'The feature of "Parliamentary Privileges" of the Indian Constitution has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'France', 'Germany'],
        correct: 1,
        explanation: 'Parliamentary Privileges has been borrowed from the United Kingdom.',
      },
      {
        question: 'The Quasi-federal form of government in the Indian Constitution has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'France', 'Canada'],
        correct: 3,
        explanation: 'The Quasi-federal form of government in the Indian Constitution has been borrowed from the Canada.',
      },
      {
        question: 'In which of the following countries the system of judicial review was originated?',
        options: ['United States of America', 'United Kingdom', 'France', 'Canada'],
        correct: 0,
        explanation: 'The system of judicial review was originated in the United States of America.',
      },
      {
        question: 'From which of the following are the Fundamental Duties adopted in the Indian Constitution?',
        options: ['United States of America', 'United Kingdom', 'Russia', 'Canada'],
        correct: 2,
        explanation: 'The Fundamental Duties adopted in the Indian Constitution have been borrowed from the Russia.',
      },
      {
        question: 'The idea of having a provision for a Bicameral Parliament in the Indian Constitution has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'Russia', 'Canada'],
        correct: 1,
        explanation: 'The idea of having a provision for a Bicameral Parliament in the Indian Constitution has been borrowed from the United Kingdom.',
      },
      {
        question: 'The cabinet system of the Indian Constitution has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'Russia', 'Canada'],
        correct: 1,
        explanation: 'The cabinet system of the Indian Constitution has been borrowed from the United Kingdom.',
      },
      {
        question: 'In India, the principle of procedure established by law has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'Japan', 'Canada'],
        correct: 2,
        explanation: 'The principle of procedure established by law has been borrowed from the Japan.',
      },
      {
        question: 'Inspired by the constitution of which of the following nations, India has added the feature of "Directive Principles of State Policy" in its Constitution?',
        options: ['United States of America', 'Ireland', 'Japan', 'Canada'],
        correct: 1,
        explanation: 'The feature of "Directive Principles of State Policy" in the Indian Constitution has been borrowed from the Ireland.',
      },
      {
        question: 'The concept of liberty, equality and fraternity (contained in the preablem of the Indian Constitution) has been borrowed from the constitution of which country?',
        options: ['United States of America', 'United Kingdom', 'France', 'Canada'],
        correct: 2,
        explanation: 'The concept of liberty, equality and fraternity (contained in the preablem of the Indian Constitution) has been borrowed from the France.',
      },
      {
        question: 'Which of the following acts introduced federal features and provincial autonomy in the legislature and also made provisions for the distribution of legislative powers between the Centre and the Provinces?',
        options: ['Indian Councils Act 1909', 'The Government of India Act, 1935', 'The Government of India Act, 1919', 'The Government of India Act, 1926'],
        correct: 1,
        explanation: 'The Government of India Act, 1935 introduced federal features and provincial autonomy in the legislature and also made provisions for the distribution of legislative powers between the Centre and the Provinces.',
      },
      {
        question: 'The provision of the speaker and his role of the Indian Constitution are borrowed from the ________ Constitution?',
        options: ['British', 'American', 'Canadian', 'Australian'],
        correct: 0,
        explanation: 'The provision of the speaker and his role of the Indian Constitution are borrowed from the British Constitution.',
      },
      {
        question: 'According to the Indian Constitution, which of the following is NOT a fundamental duty?',
        options: ['To protect public property', 'To promote the feeling of brotherhood', 'To follow the constitution and respects its identity', 'Voting in Public Elections'],
        correct: 3,
        explanation: 'Voting in Public Elections is NOT a fundamental duty.',
      },
      {
        question: 'Which of the following options is NOT included in the Fundamental Duties of the Indian Constitution?',
        options: ['Focussing only on personal development and personal activity', 'Respecting the National flag and National anthem', 'To value and preserve the rich heritage of our composite culture', 'To maintain and protect the sovereignty, unity and integrity of the nation'],
        correct: 0,
        explanation: 'Focussing only on personal development and personal activity is NOT included in the Fundamental Duties of the Indian Constitution.',
      },
      
    ],
    'quiz-4': [
      {
        question: 'A money bill after having been passed by the Lok Sabha, and sent to Rajya Sabha for its recommendations, has to be returned to Lok Sabha by the Rajya Sabha, within a period of __________ from the date of its receipt, with or without recommendations',
        options: ['14 days', '16 days', '18 days', '20 days'],
        correct: 0,
        explanation: 'A money bill after having been passed by the Lok Sabha, and sent to Rajya Sabha for its recommendations, has to be returned to Lok Sabha by the Rajya Sabha, within a period of 14 days from the date of its receipt, with or without recommendations.',
      },
      {
        question: 'The Rajya Sabha members are elected for a terms of how many years?',
        options: ['4', '5', '6', '7'],
        correct: 0,
        explanation: 'The Rajya Sabha members are elected for a terms of 6 years.',
      },
      {
        question: 'Which bill can not originate in Rajya Sabha?',
        options: ['Money Bill', 'Constitutional Amendment Bill', 'Fundamental Bill', 'Ordinary Bill'],
        correct: 1,
        explanation: 'Money Bill can not originate in Rajya Sabha.',
      },
      {
        question: 'Who is the Chairman of the Rajya Sabha?',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Deputy Speaker of Rajya Sabha'],
        correct: 1,
        explanation: 'Vice President of India is the Chairman of the Rajya Sabha.',
      },
      {
        question: 'In which of the following years was the council of states (Rajya Sabha) first constituted?',
        options: ['1952', '1953', '1954', '1955'],
        correct: 0,
        explanation: 'The council of states (Rajya Sabha) was first constituted in 1952.',
      },
      {
        question: 'How many members of the Rajya Sabha are elected every two years?',
        options: ['All', 'Half', 'One-third', 'One-fourth'],
        correct: 2,
        explanation: 'One-third members of the Rajya Sabha are elected every two years.',
      },
      {
        question: 'Out of 552 members of the Rajya Sabha, how many are elected from the states?',
        options: ['530', '535', '540', '545'],
        correct: 0,
        explanation: '530 members of the Rajya Sabha are elected from the states.',
      },
      {
        question: 'Who among the following decides whether a particular bill is a money bill or not?',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Deputy Speaker of Rajya Sabha'],
        correct: 2,
        explanation: 'Speaker of Lok Sabha decides whether a particular bill is a money bill or not.',
      },
      {
        question: 'Who was the first woman speaker of Lok Sabha?',
        options: ['Meira Kumar', 'Meira Gandhi', 'Sushma Swaraj', 'Sumitra Mahajan'],
        correct: 0,
        explanation: 'Meira Kumar was the first woman speaker of Lok Sabha.',
      },
      {
        question: 'After question hour, a motion movd by a member of parliament to draw the attention of the executive for discussing a definite matter of public importance is called __________',
        options: ['Calling attention motion', 'Adjournment motion', 'No-confidence motion', 'Privilege motion'],
        correct: 1,
        explanation: 'Adjournment motion is called after question hour, a motion movd by a member of parliament to draw the attention of the executive for discussing a definite matter of public importance.',
      },
      {
        question: 'Who presides over the jint sitting of the Lok Sabha and the Rajya Sabha?',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Deputy Speaker of Rajya Sabha'],
        correct: 2,
        explanation: 'Speaker of Lok Sabha presides over the jint sitting of the Lok Sabha.',
      },
      {
        question: 'Vote of No-confidence motion is brought in which house?',
        options: ['Lok Sabha', 'Rajya Sabha', 'Both', 'None of the above'],
        correct: 0,
        explanation: 'Vote of No-confidence motion is brought in the Lok Sabha.',
      },
      {
        question: 'The President of India can dissolve the Lok Sabha before completion of term __________',
        options: ['On the advice of the Prime Minister', 'On the advice of the President', 'On the advice of the Speaker of Lok Sabha', 'On the advice of the Deputy Speaker of Lok Sabha'],
        correct: 0,
        explanation: 'The President of India can dissolve the Lok Sabha before completion of term on the advice of the Prime Minister.',
      },
      {
        question: 'Who among the following was the deputy speaker of the first Lok Sabha?',
        options: ['AK Gopalan', 'MN Kaul', 'Rabi Ray', 'M A Ayangar'],
        correct: 3,
        explanation: 'M A Ayangar was the deputy speaker of the first Lok Sabha.',
      },
      {
        question: 'The minimum number of members that must be present to hold the meeting of the Lok Sabha is __________',
        options: ['One-fourth of the total membership', 'One-tenth of the total membership', 'Fifty percent of the total membership', 'At least 100 members'],
        correct: 1,
        explanation: 'One-tenth of the total membership is the minimum number of members that must be present to hold the meeting of the Lok Sabha.',
      },
      {
        question: 'The parliament form of government is also referred to as the ______________ model',
        options: ['Communist', 'Plutocracy', 'Theocracy', 'Westminster'],
        correct: 3,
        explanation: 'The parliament form of government is also referred to as the Westminster model.',
      },
      {
        question: 'How many sessions of the Lok Sabha are normally held in a year?',
        options: ['1', '2', '3', '4'],
        correct: 2,
        explanation: '3 sessions of the Lok Sabha are normally held in a year.',
      },
      {
        question: 'Who decides on the issue related to the dis-qualification of a member of Lok Sabha under Tenth Schedule of the Indian Constitution?',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Deputy Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Speaker of Lok Sabha decides on the issue related to the dis-qualification of a member of Lok Sabha under Tenth Schedule of the Indian Constitution.',
      },
      {
        question: 'Which of the following articles of the Indian Constitution provides for the Bicameral Parliament of India?',
        options: ['Article 76', 'Article 77', 'Article 78', 'Article 79'],
        correct: 3,
        explanation: 'Article 79 provides for the Bicameral Parliament of India.',
      },
      {
        question: 'Who decides disputes regarding the dis-qualification of members of Parliament?',
        options: ['President of India', 'Election Commission', 'The Prime Minister in consultation with the Election Commission', 'The President in consultation with the Election Commission'],
        correct: 3,
        explanation: 'The President in consultation with the Election Commission decides disputes regarding the dis-qualification of members of Parliament.',
      },
      {
        question: 'What is the Quorum laid down to constitute a meeting of either of the houses of Parliament?',
        options: ['One-third', 'One-fifth', 'One-tenth', 'One-twelfth'],
        correct: 2,
        explanation: 'One-tenth is the Quorum laid down to constitute a meeting of either of the houses of Parliament.',
      },
      {
        question: 'In the context of the Indian Parliament, what is zero-hour?',
        options: ['Time in the first half of the Parliamentary proceeding', 'Time immediately after question hour', 'Time before question hour', 'Time in the last half of the Parliamentary proceeding'],
        correct: 1,
        explanation: 'Time immediately after question hour is zero-hour.',
      },
    ],
    'quiz-5': [
      {
        question: 'How many other members are there in the Finance Commission EXCEPT, Chairman?',
        options: ['3', '4', '5', '6'],
        correct: 1,
        explanation: '4 other members are there in the Finance Commission EXCEPT, Chairman.',
      },
      {
        question: 'In which of the following years was the Election Commission of India established?',
        options: ['1950', '1951', '1952', '1953'],
        correct: 0,
        explanation: 'The Election Commission of India was established in 1950.',
      },
      {
        question: 'What is the tenure of office of the Chief Election Commissioner?',
        options: ['5 years or upto age of 60 years', '5 years or upto age of 65 years', '6 years or upto age of 60 years', '6 years or upto age of 65 years'],
        correct: 3,
        explanation: '6 years or upto age of 65 years is the tenure of office of the Chief Election Commissioner.',
      },
      {
        question: 'Who among the is NOT a member of the National Human Rights Commission?',
        options: ['District Magistrate', 'Former Chief Justice of the High Court', 'Former Judge of the Supreme Court', 'Former Chief Justice of the Supreme Court'],
        correct: 0,
        explanation: 'District Magistrate is NOT a member of the National Human Rights Commission.',
      },
      {
        question: 'Which part of the Indian Constitution deals with the Election Commission of India?',
        options: ['Part XIII', 'Part XIV', 'Part XV', 'Part XVI'],
        correct: 2,
        explanation: 'Part XV deals with the Election Commission of India.',
      },
      {
        question: 'UPSC is a Constitutional Body to conduct examinations for appointments to the services of the Union and the services of the State, respectively, under Article ________ of the Constitution of India?',
        options: ['Article 320', 'Article 321', 'Article 322', 'Article 323'],
        correct: 2,
        explanation: 'Article 320 of the Constitution of India deals with the Union Public Service Commission.',
      },
      {
        question: 'The establishment of Union Public Service Commission, State Public Service Commissions and Joint Public Service Commission falls under which of the following features of the Indian Constitution?',
        options: ['Directive Principles of State Policy', 'Fundamental Rights', 'Federalism', 'Parliamentary System'],
        correct: 2,
        explanation: 'Federalism falls under the establishment of Union Public Service Commission, State Public Service Commissions and Joint Public Service Commission.',
      },
      {
        question: 'Which Article of the Indian Constitution mentions about the recommendations of the Finance Commission?',
        options: ['Article 280', 'Article 281', 'Article 282', 'Article 283'],
        correct: 1,
        explanation: 'Article 281 of the Constitution of India mentions about the recommendations of the Finance Commission.',
      },
      {
        question: 'What is the maximum age for a member of a joint public service commission to hold his/her officer as per the Indian Constitution?',
        options: ['60 years', '62 years', '63 years', '65 years'],
        correct: 1,
        explanation: '62 years is the maximum age for a member of a joint public service commission to hold his/her officer as per the Indian Constitution.',
      },
      {
        question: 'Who was the first Chairman of the Finance Commission of India?',
        options: ['Ashok Kumar Chanda', 'K Santhanam', 'KC Neogy', 'PV Rajamannar'],
        correct: 2,
        explanation: 'KC Neogy was the first Chairman of the Finance Commission of India.',
      },
      {
        question: 'Under which of the following Acts was the National Commission for Women established?',
        options: ['The National Commission for Women Act, 1987', 'The National Commission for Women Act, 1988', 'The National Commission for Women Act, 1989', 'The National Commission for Women Act, 1990'],
        correct: 3,
        explanation: 'The National Commission for Women Act, 1990 was the Act under which the National Commission for Women was established.',
      },
      {
        question: 'Who appoints the State Election Commissioners?',
        options: ['Chief Minister', 'Governor', 'President', 'Advocate General'],
        correct: 1,
        explanation: 'Governor appoints the State Election Commissioners.',
      },
      {
        question: 'The Chairman of a State Public Service Commission can be removed by the order of the __________',
        options: ['Chief Minister', 'Governor', 'President', 'Advocate General'],
        correct: 2,
        explanation: 'President can remove the Chairman of a State Public Service Commission by the order of the President.',
      },
      {
        question: 'Which of the following is NOT a Constitutional Body in India?',
        options: ['Election Commission of India', 'State Human Rights Commission', 'State Public Service Commission', 'Union Public Service Commission'],
        correct: 1,
        explanation: 'State Human Rights Commission is NOT a Constitutional Body in India.',
      },
      {
        question: 'The elections to the Panchayati Raj Institutions are conducted by the __________',
        options: ['Election Commission of India', 'State Election Commission', 'Union Election Commission', 'State Public Service Commission'],
        correct: 1,
        explanation: 'State Election Commission conducts the elections to the Panchayati Raj Institutions.',
      },
      {
        question: 'What is the tenure of the Chairperson of National Human Rights Commission?',
        options: ['3 years', '4 years', '5 years', '6 years'],
        correct: 0,
        explanation: '3 years is the tenure of the Chairperson of National Human Rights Commission.',
      },
      {
        question: 'In which year was the National Commission for Women established in India?',
        options: ['1990', '1991', '1992', '1993'],
        correct: 3,
        explanation: '1993 is the year in which the National Commission for Women was established in India.',
      },
      {
        question: '',
        options: ['District Magistrate', 'Former Chief Justice of the High Court', 'Former Judge of the Supreme Court', 'Former Chief Justice of the Supreme Court'],
        correct: 0,
        explanation: 'District Magistrate is NOT a member of the National Commission for Protection for Child Rights.',
      },
      
      
      
      
      
    ],
    'quiz-6': [
      {
        question: 'In India, who among the following has the power to pardon, remit or commute the punishment of a criminal',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Prime Minister'],
        correct: 0,
        explanation: 'President of India has the power to pardon, remit or commute the punishment of a criminal .',
      },
      {
        question: 'Which of the following statements in NOT correct regarding the election of the Vice President of India?',
        options: ['He should be a citizen of India', 'He is eligible to contest elections as a member of the Rajya Sabha', 'He is eligible to contest elections as a member of the Lok Sabha', 'He should be above 35 years of age'],
        correct: 2,
        explanation: 'He is eligible to contest elections as a member of the Lok Sabha is NOT correct regarding the election of the Vice President of India.',
      },
      {
        question: 'A bill becomes an Act of the Parliament after being passed by both the Houses of Parliament and assented to by the __________',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Prime Minister'],
        correct: 0,
        explanation: 'President of India is the one who assented to the bill becomes an Act of the Parliament after being passed by both the Houses of Parliament and assented to by the President of India.',
      },
      {
        question: 'Which of the following Articles of the Constitution of India states that there will be Vice President of India',
        options: ['Article 61', 'Article 62', 'Article 63', 'Article 64'],
        correct: 2,
        explanation: 'Article 63 of the Constitution of India states that there will be Vice President of India.',
      },
      {
        question: 'Which of the following Articles of Constitution of India deals with the manner of election of the President of India',
        options: ['Article 55', 'Article 56', 'Article 57', 'Article 58'],
        correct: 0,
        explanation: 'Article 55 of the Constitution of India deals with the manner of election of the President of India.',
      },
      {
        question: 'The President of India has the power to pardon under which article of the Constitution of India?',
        options: ['Article 70', 'Article 71', 'Article 72', 'Article 73'],
        correct: 2,
        explanation: 'Article 72 of the Constitution of India has the power to pardon.',
      },
      {
        question: 'As per the Constitution of India, who is authorised to transfer the Judge of the High Court to another High Court?',
        options: ['President of India', 'Governor of the State', 'Chief Justice of the High Court', 'Chief Justice of the Supreme Court'],
        correct: 0,
        explanation: 'President of India is the one who is authorised to transfer the Judge of the High Court to another High Court.',
      },
      {
        question: 'With whose consultation does the President of India convene ad prorogue Parliament?',
        options: ['The Speaker', 'The Prime Minister', 'The Council of Ministers', 'The Prime Minister and the leader of the opposition in Lok Sabha'],
        correct: 1,
        explanation: 'The Prime Minister is the one who is authorised to convene ad prorogue Parliament.',
      },
      {
        question: 'In case of death of the President and Vice President of India, who will act as the President of India?',
        options: ['Attorney General of India', 'Chief Justice of Supreme Court', 'Prime Minister of India', 'Parliament chosen candidate'],
        correct: 1,
        explanation: 'Chief Justice of Supreme Court will act as the President of India in case of death of the President and Vice President of India.',
      },
      {
        question: 'How many members can be nominated by the President of India in the Rajya Sabha?',
        options: ['8', '10', '12', '14'],
        correct: 2,
        explanation: '12 members can be nominated by the President of India in the Rajya Sabha.',
      },
      {
        question: 'Who has the right to investigate and decide all the doubts and controversies arising out of the election of the President of India?',
        options: ['Supreme Court of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Lokpal'],
        correct: 0,
        explanation: 'Supreme Court of India has the right to investigate and decide all the doubts and controversies arising out of the election of the President of India.',
      },
      {
        question: 'Under which article of the Constitution of India can the President of India promulgate an ordinance?',
        options: ['Article 120', 'Article 121', 'Article 122', 'Article 123'],
        correct: 3,
        explanation: 'Article 123 of the Constitution of India can the President of India promulgate an ordinance.',
      },
      {
        question: 'Who is nominal executive authority of India?',
        options: ['President of India', 'Vice President of India', 'Speaker of Lok Sabha', 'Prime Minister'],
        correct: 1,
        explanation: 'President of India is the nominal executive authority of India.',
      },
      {
        question: 'Which of the following is NOT an eligibility requirement to become the Vice President of India?',
        options: ['He should be a citizen of India', 'He should have completed 40 years of age', 'He should be qualified to be as a member of Rajya Sabha', 'They should not hold any office of profit under the Government of India or the Government of any State'],
        correct: 1,
        explanation: 'He should have completed 40 years of age is NOT an eligibility requirement to become the Vice President of India.',
      },
      {
        question: 'Which of the following statement is CORRECT',
        options: ['The Governor can dissolve the Legislative Assembly of a State', 'The Speaker of the Lok Sabha can dissolve the Lok Sabha', 'The President of India can dissolve the Rajya Sabha', 'The Vice President of India can dissolve the Legislative Assembly of a State'],
        correct: 0,
        explanation: 'The Governor can dissolve the Legislative Assembly of a State is CORRECT.',
      },
      {
        question: 'Which Article of the Constitution of India deals with the "Pardoning Power of the Governor"',
        options: ['Article 160', 'Article 161', 'Article 162', 'Article 163'],
        correct: 1,
        explanation: 'Article 161 of the Constitution of India deals with the "Pardoning Power of the Governor".',
      },
      {
        question: 'Who was the first Woman Governor of an Indian State?',
        options: ['Sarojini Naidu', 'Sucheta Kripalani', 'Padmaja Naidu', 'Tarkeswari Sinha'],
        correct: 0,
        explanation: 'Sarojini Naidu was the first Woman Governor of an Indian State.',
      },
      
    ],
    'quiz-7': [
      {
        question: 'Who is the real executive head of the Union Government in India?',
        options: ['President of India', 'Vice President of India', 'Prime Minister', 'Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Prime Minister is the real executive head of the Union Government in India.',
      },
      {
        question: 'The Prime Minister of India is appointed by the __________',
        options: ['President of India', 'Vice President of India', 'Parliament', 'Council of Ministers'],
        correct: 0,
        explanation: 'President of India is the one who appoints the Prime Minister of India.',
      },
      {
        question: 'The Prime Minister of India must be a member of __________',
        options: ['Lok Sabha', 'Rajya Sabha', 'Either Lok Sabha or Rajya Sabha', 'Neither Lok Sabha nor Rajya Sabha'],
        correct: 2,
        explanation: 'The Prime Minister of India must be a member of Either Lok Sabha or Rajya Sabha.',
      },
      {
        question: 'Who presides over the meetins of the Union Cabinet?',
        options: ['President of India', 'Vice President of India', 'Prime Minister', 'Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Prime Minister presides over the meetins of the Union Cabinet.',
      },
      {
        question: 'Which Article of the Constitution of India mentions the Prime Minister of India?',
        options: ['Article 74', 'Article 75', 'Article 78', 'All of the above'],
        correct: 3,
        explanation: 'All of the above Articles mention the Prime Minister of India.',
      },
      {
        question: 'Who acts as the link between the President and Council of Ministers?',
        options: ['President of India', 'Vice President of India', 'Prime Minister', 'Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Prime Minister acts as the link between the President and Council of Ministers.',
      },
      {
        question: 'In the event of the death or resignation of the Prime Minister, the Council of Ministers',
        options: ['Continues', 'Automatically dissolves', 'Is headed by the President', 'Stay until Parliament is dissolved'],
        correct: 1,
        explanation: 'Automatically dissolves in the event of the death or resignation of the Prime Minister.',
      },
      {
        question: 'Who prepares the list of Portfolios for the Council of Ministers?',
        options: ['President of India', 'Vice President of India', 'Prime Minister', 'Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Prime Minister prepares the list of Portfolios for the Council of Ministers.',
      },
      {
        question: 'Which body is responsible for making major policy decisions in India?',
        options: ['Lok Sabha', 'Planning Commission', 'President of India', 'Union Cabinet'],
        correct: 3,
        explanation: 'Union Cabinet is responsible for making major policy decisions in India.',
      },
      {
        question: 'Who is the real executive head of a state?',
        options: ['Governor', 'Chief Minister', 'Chief Secretary', 'State Assembly Speaker'],
        correct: 1,
        explanation: 'Chief Minister is the real executive head of a state.',
      },
      {
        question: 'Who appoints the Chief Minister of a state?',
        options: ['President of India', 'Governor of the State', 'Chief Justice of the High Court', 'Speaker of Lok Sabha'],
        correct: 1,
        explanation: 'Governor of the State appoints the Chief Minister of a state.',
      },
      {
        question: 'Which Article of the Constitution of India deals with the "Appointment of the Chief Minister of a State"?',
        options: ['Article 164', 'Article 165', 'Article 166', 'Article 167'],
        correct: 0,
        explanation: 'Article 164 of the Constitution of India deals with the "Appointment of the Chief Minister of a State".',
      },
      {
        question: 'What is the maximum term of a Chief Minister of a State?',
        options: ['4 years', '5 years', '6 years', 'No fixed term'],
        correct: 3,
        explanation: 'No fixed term is the maximum term of a Chief Minister of a State.',
      },
      {
        question: 'The Chief Minister communicates all administrative decisions to__________',
        options: ['President of India', 'Governor of the State', 'Chief Justice of the High Court', 'State Assembly Speaker'],
        correct: 1,
        explanation: 'Governor of the State is the one who communicates all administrative decisions to the Chief Minister.',
      },  
      {
        question: 'Who allocates the portfolios among the state ministers?',
        options: ['Governor of the State', 'Chief Minister', 'Chief Justice of the High Court', 'State Assembly Speaker'],
        correct: 1,
        explanation: 'Chief Minister allocates the portfolios among the state ministers.',
      },
      {
        question: 'In case of resignation of Chief Minister, the Council of Ministers',
        options: ['Continues', 'Automatically dissolves', 'Is headed by the Governor', 'Is reappointed by the Governor'],
        correct: 1,
        explanation: 'Automatically dissolves in case of resignation of Chief Minister.',
      },
      {
        question: 'The Chief Minister is required to be a member of the state legislature within:',
        options: ['3 months', '4 months', '6 months', '1 year'],
        correct: 2,
        explanation: '6 months is the time required for the Chief Minister to be a member of the state legislature.',
      },
      {
        question: 'Which Article of the Constitution of India deals with the duties of Chief Minister to communicate with the Governor?',
        options: ['Article 164', 'Article 165', 'Article 166', 'Article 167'],
        correct: 3,
        explanation: 'Article 167 of the Constitution of India deals with the duties of Chief Minister to communicate with the Governor.',
      },
      {
        question: 'Chief Minister is the head of the',
        options: ['State Government', 'Union Government', 'State Legislature', 'Council of Ministers'],
        correct: 0,
        explanation: 'Chief Minister is the head of the State Government.',
      },
      {
        question: 'The Council of Ministers is collectively responsible for',
        options: ['Lok Sabha', 'Rajya Sabha', 'President', 'Supreme Court'],
        correct: 0,
        explanation: 'Lok Sabha is collectively responsible for the Council of Ministers.',
      },
      {
        question: 'What is the maximum number of ministers in a state including the Chief Minister?',
        options: ['10% of the total members', '15% of the total members', '20% of the total members', '25% of the total members'],
        correct: 1,
        explanation: '15% of the total members is the maximum number of ministers in a state including the Chief Minister (As per 91st Amendment).',
      },
      {
        question: 'Ministers hold office during the peasure of the:',
        options: ['Prime Minister', 'President', 'Parliament', 'Supreme Court'],
        correct: 1,
        explanation: 'President is the one who holds office during the peasure of the President.',
      },
      {
        question: 'The Council of Ministers includes the',
        options: ['Cabinet Ministers only', 'Minister of State only', 'Deputy Ministers only', 'All of the above'],
        correct: 3,
        explanation: 'All of the above are members of the Council of Ministers.',
      },
      {
        question: 'Who decides the rank of ministers in the Council of Ministers?',
        options: ['President of India', 'Vice President of India', 'Prime Minister', 'Speaker of Lok Sabha'],
        correct: 2,
        explanation: 'Prime Minister decides the rank of ministers in the Council of Ministers.',
      },
      
      
    ],
    'quiz-8': [
      {
        question: 'If the President neither signs nor returns a bill, it is consider as:',
        options: ['Absolute veto', 'Pocket veto', 'Suspensive veto', 'Line-term veto'],
        correct: 1,
        explanation: 'Pocket veto is the one who is considered as if the President neither signs nor returns a bill.',
      },
    ],
  },
}